**DIABETES PERDECTION USING ANN**

PRE-PROCESSINGS

In [ ]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Diabetes prediction using ANN/diabetes_prediction_dataset.csv")
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [ ]:
df = df[df['smoking_history'] != 'No Info']
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
5      Female  20.0             0              0           never  27.32   
...       ...   ...           ...            ...             ...    ...   
99992  Female  26.0             0              0           never  34.34   
99993  Female  40.0             0              0           never  40.69   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
5              6.6                   85         0  
...            ...                  ...       ...  
99992          6.5                  160         0  
99993          3.5                  155         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[64184 rows x 9 columns]

In [ ]:
df['smoking_history'] = df['smoking_history'].replace({'never': 0, 'current': 1, 'former': 1 , 'not current': 1 , 'ever':0})
df

<ipython-input-3-76eec7b800e6>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['smoking_history'] = df['smoking_history'].replace({'never': 0, 'current': 1, 'former': 1 , 'not current': 1 , 'ever':0})


gender   age  hypertension  heart_disease  smoking_history    bmi  \
0      Female  80.0             0              1                0  25.19   
2        Male  28.0             0              0                0  27.32   
3      Female  36.0             0              0                1  23.45   
4        Male  76.0             1              1                1  20.14   
5      Female  20.0             0              0                0  27.32   
...       ...   ...           ...            ...              ...    ...   
99992  Female  26.0             0              0                0  34.34   
99993  Female  40.0             0              0                0  40.69   
99997    Male  66.0             0              0                1  27.83   
99998  Female  24.0             0              0                0  35.42   
99999  Female  57.0             0              0                1  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
5              6.6                   85         0  
...            ...                  ...       ...  
99992          6.5                  160         0  
99993          3.5                  155         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[64184 rows x 9 columns]

In [ ]:
dummies=pd.get_dummies(df.gender)
df1=pd.concat([df,dummies.drop("Other",axis=1)],axis=1)
df1.drop("gender",axis=1,inplace=True)

In [ ]:
df1

age  hypertension  heart_disease  smoking_history    bmi  HbA1c_level  \
0      80.0             0              1                0  25.19          6.6   
2      28.0             0              0                0  27.32          5.7   
3      36.0             0              0                1  23.45          5.0   
4      76.0             1              1                1  20.14          4.8   
5      20.0             0              0                0  27.32          6.6   
...     ...           ...            ...              ...    ...          ...   
99992  26.0             0              0                0  34.34          6.5   
99993  40.0             0              0                0  40.69          3.5   
99997  66.0             0              0                1  27.83          5.7   
99998  24.0             0              0                0  35.42          4.0   
99999  57.0             0              0                1  22.43          6.6   

       blood_glucose_level  diabetes  Female  Male  
0                      140         0       1     0  
2                      158         0       0     1  
3                      155         0       1     0  
4                      155         0       0     1  
5                       85         0       1     0  
...                    ...       ...     ...   ...  
99992                  160         0       1     0  
99993                  155         0       1     0  
99997                  155         0       0     1  
99998                  100         0       1     0  
99999                   90         0       1     0  

[64184 rows x 10 columns]

**TRAIN-TEST SPLIT**

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
X = df1.drop('diabetes', axis=1)
y = df1['diabetes']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

**Building the model**

In [ ]:
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=X_train_scaled.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, verbose=1)

Epoch 1/10
1605/1605 [==============================] - 18s 5ms/step - loss: 0.1531 - accuracy: 0.9448
Epoch 2/10
1605/1605 [==============================] - 5s 3ms/step - loss: 0.1266 - accuracy: 0.9543
Epoch 3/10
1605/1605 [==============================] - 7s 4ms/step - loss: 0.1144 - accuracy: 0.9583
Epoch 4/10
1605/1605 [==============================] - 5s 3ms/step - loss: 0.1084 - accuracy: 0.9605
Epoch 5/10
1605/1605 [==============================] - 7s 4ms/step - loss: 0.1052 - accuracy: 0.9618
Epoch 6/10
1605/1605 [==============================] - 5s 3ms/step - loss: 0.1040 - accuracy: 0.9619
Epoch 7/10
1605/1605 [==============================] - 6s 4ms/step - loss: 0.1030 - accuracy: 0.9627
Epoch 8/10
1605/1605 [==============================] - 6s 4ms/step - loss: 0.1023 - accuracy: 0.9630
Epoch 9/10
1605/1605 [==============================] - 5s 3ms/step - loss: 0.1018 - accuracy: 0.9628
Epoch 10/10
1605/1605 [==============================] - 7s 4ms/step - loss: 0.10

**Accuracy**

In [ ]:
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

402/402 [==============================] - 1s 2ms/step - loss: 0.1051 - accuracy: 0.9637
Test Loss: 0.10510598123073578
Test Accuracy: 0.96369868516922


In [ ]:
X.columns

Index(['age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi',
       'HbA1c_level', 'blood_glucose_level', 'Female', 'Male'],
      dtype='object')

**PREDICTION**

In [ ]:
import numpy as np

def predict_diabetes(age, hypertension, heart_disease, smoking_history, bmi, HbA1c_level, blood_glucose_level, gender):
    loc_index = np.where(X.columns == gender)[0][0]
    a = np.zeros(len(X.columns))
    a[0] = age
    a[1] = hypertension
    a[2] = heart_disease
    a[3] = smoking_history
    a[4] = bmi
    a[5] = HbA1c_level
    a[6] = blood_glucose_level
    if loc_index >= 0:
        a[loc_index] = 1

    a = np.reshape(a, (1, -1))

    RESULT = model.predict(a)[0]
    print(RESULT)
    #if RESULT == 1:
        #print("You have diabetes.")
    #else:
        #print("No,You dont have diabetes.")
    return RESULT


In [ ]:
predict_diabetes(55,1,1,1,26,12,160,"Female")

1/1 [==============================] - 0s 74ms/step
[1.]


array([1.], dtype=float32)

In [ ]:
predict_diabetes(55,1,1,1,26,12,160,"Male")

1/1 [==============================] - 0s 18ms/step
[1.]


array([1.], dtype=float32)

In [ ]:
predict_diabetes(20,0,0,0,20,12,120,"Male")

1/1 [==============================] - 0s 19ms/step
[1.]


array([1.], dtype=float32)

In [ ]:
predict_diabetes(20,0,0,0,0,0,60,"Male")

1/1 [==============================] - 0s 20ms/step
[1.]


array([1.], dtype=float32)

In [ ]:
predict_diabetes(80.0,0,1,0,25.19,6.6,0,"Female")

1/1 [==============================] - 0s 21ms/step
[1.]


array([1.], dtype=float32)

**SAVING MODEL**

In [ ]:
import pickle
filename = '/content/drive/MyDrive/Diabetes prediction using ANN/diabetes_predictor.pkl'
pickle.dump(model, open(filename, 'wb'))

**BY Vishnu Jayanth S**